import { useQuery } from "convex/react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Check, CircleAlert, Clock3, Globe2, MailCheck, Route, Send, ShieldCheck } from "lucide-react";
import { api } from "../../convex/_generated/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function PublicJourneyPage() {
  const { slug = "" } = useParams();
  const report = useQuery(api.journeys.getPublic, { slug });
  if (report === undefined) return <main className="grid min-h-screen place-items-center bg-[#0b0e0c] text-[#f3efe6]"><span className="size-4 animate-pulse rounded-full bg-[#c8ff53]" /><span className="sr-only">Loading public journey report</span></main>;
  if (report === null) return <main className="grid min-h-screen place-items-center bg-[#f3efe6] p-6"><div className="max-w-lg text-center"><p className="eyebrow">Public proof</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.06em]">This report is not available.</h1><Button asChild className="mt-7 rounded-full"><Link to="/">Back to Signal Garden</Link></Button></div></main>;
  return (
    <div className="min-h-screen bg-[#f3efe6] text-[#111612]">
      <header className="flex h-[72px] items-center justify-between border-b border-black/20 px-5 md:px-8 lg:px-12"><Link to="/" className="flex items-center gap-2 font-semibold"><ArrowLeft className="size-4" /> Signal Garden</Link><Badge variant="outline" className="border-black/25 bg-transparent"><ShieldCheck className="size-3" /> Customer-safe evidence</Badge></header>
      <main>
        <section className="border-b border-black/20 px-5 py-12 md:px-8 lg:px-12 lg:py-16">
          <div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow">{report.businessName} · {report.websiteDomain}</p><h1 className="mt-5 max-w-5xl text-6xl font-semibold leading-[.86] tracking-[-.07em] md:text-8xl">{report.name}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-black/65">{report.goal}</p></div><div className={report.latestRun.status === "healthy" ? "border border-[#4f7134]/35 bg-[#4f7134]/8 p-6" : "border border-[#d54f3d]/35 bg-[#d54f3d]/8 p-6"}><p className="eyebrow">Current outcome</p><div className="mt-4 flex items-center gap-3">{report.latestRun.status === "healthy" ? <Check className="size-7 text-[#4f7134]" /> : <CircleAlert className="size-7 text-[#d54f3d]" />}<span className="text-3xl font-semibold capitalize tracking-[-.045em]">{report.latestRun.status}</span></div><p className="mt-3 max-w-xs text-sm leading-relaxed text-black/65">{report.latestRun.summary ?? "The latest run is still producing evidence."}</p></div></div>
        </section>
        {report.openIncident && <section className="border-b border-[#d54f3d]/35 bg-[#d54f3d]/8 px-5 py-7 md:px-8 lg:px-12"><div className="flex max-w-5xl items-start gap-4"><CircleAlert className="mt-1 size-5 shrink-0 text-[#d54f3d]" /><div><p className="font-semibold">{report.openIncident.title}</p><p className="mt-1 text-sm text-black/55">{report.openIncident.detail}</p></div></div></section>}
        <section className="px-5 py-14 md:px-8 lg:px-12 lg:py-20"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Latest real run</p><h2 className="mt-4 text-5xl font-semibold tracking-[-.06em]">Every handoff, one record.</h2></div><p className="text-xs text-black/60">Started {new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(report.latestRun.startedAt)}</p></div><div className={`mt-10 grid gap-px border border-black/20 bg-black/20 md:grid-cols-2 ${report.latestRun.checkpoints.length === 3 ? "xl:grid-cols-3" : "xl:grid-cols-4"}`}>{report.latestRun.checkpoints.map((checkpoint) => <article key={checkpoint._id} className="min-h-60 bg-[#f3efe6] p-6"><div className="flex items-center justify-between"><PublicCheckpointIcon kind={checkpoint.kind} status={checkpoint.status} /><span className="font-mono text-[10px] uppercase tracking-[.14em] text-black/60">{checkpoint.status}</span></div><h3 className="mt-12 text-2xl font-semibold tracking-[-.04em]">{checkpoint.kind === "confirmation" ? "Confirmation issued" : checkpoint.label}</h3><p className="mt-3 text-sm leading-relaxed text-black/65">{checkpoint.detail ?? "No evidence recorded for this handoff yet."}</p>{checkpoint.evidenceExcerpt && <p className="mt-4 border-l-2 border-[#4f7134] pl-3 text-xs leading-relaxed text-black/65">{checkpoint.evidenceExcerpt}</p>}</article>)}</div><div className="mt-8 border border-black/15 p-5 text-sm leading-relaxed text-black/65"><ShieldCheck className="mr-2 inline size-4 text-[#4f7134]" /> This public report excludes form contents, customer identities, inbox addresses, private team notes, internal provider identifiers, and secrets.</div></section>
      </main>
    </div>
  );
}

function PublicCheckpointIcon({ kind, status }: { kind: "website" | "form" | "confirmation" | "human_reply"; status: string }) { if (status === "verified") return <span className="grid size-9 place-items-center rounded-full bg-[#4f7134] text-white"><Check className="size-4" /></span>; if (status === "failed") return <span className="grid size-9 place-items-center rounded-full bg-[#d54f3d] text-white"><CircleAlert className="size-4" /></span>; const Icon = kind === "website" ? Globe2 : kind === "form" ? Send : kind === "confirmation" ? MailCheck : kind === "human_reply" ? Clock3 : Route; return <span className="grid size-9 place-items-center rounded-full border border-black/20"><Icon className="size-4" /></span>; }
